const recipes = [
    {
      id: '52839',
      mealName: 'Chilli prawn linguine',
      mealCategory: 'Pasta',
      instructions: 'Mix the dressing ingredients in a small bowl and season with salt and pepper. Set aside.\r\n\r\nCook the pasta according to the packet instructions. Add the sugar snap peas for the last minute or so of cooking time.\r\n\r\nMeanwhile, heat the oil in a wok or large frying pan, toss in the garlic and chilli and cook over a fairly gentle heat for about 30 seconds without letting the garlic brown. Tip in the prawns and cook over a high heat, stirring frequently, for about 3 minutes until they turn pink.\r\n\r\nAdd the tomatoes and cook, stirring occasionally, for 3 minutes until they just start to soften. Drain the pasta and sugar snaps well, then toss into the prawn mixture. Tear in the basil leaves, stir, and season with salt and pepper.\r\n\r\nServe with salad leaves drizzled with the lime dressing, and warm crusty bread.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=SC17Mc70Db0',
      ingredient1: 'Linguine Pasta',
      ingredient2: 'Sugar Snap Peas',
      ingredient3: 'Olive Oil',
      ingredient4: 'Garlic Clove',
      ingredient5: 'Red Chilli',
      ingredient6: 'King Prawns',
      ingredient7: 'Cherry Tomatoes',
      ingredient8: 'Basil Leaves',
      ingredient9: 'Lettuce',
      ingredient10: 'Bread',
      ingredient11: 'Fromage Frais',
      ingredient12: 'Lime',
      ingredient13: 'Caster Sugar',
      ingredient14: '',
      ingredient15: '',
      ingredient16: '',
      ingredient17: '',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '280g',
      measure2: '200g',
      measure3: '2 tblsp ',
      measure4: '2 cloves chopped',
      measure5: '1 large',
      measure6: '24 Skinned',
      measure7: '12',
      measure8: 'Handful',
      measure9: 'Leaves',
      measure10: 'to serve',
      measure11: '2 tbsp',
      measure12: 'Grated Zest of 2',
      measure13: '2 tsp',
      measure14: '',
      measure15: '',
      measure16: '',
      measure17: '',
      measure18: '',
      measure19: '',
      measure20: ''
    },
    {
      id: '52794',
      mealName: 'Vegan Chocolate Cake',
      mealCategory: 'Vegan',
      instructions: 'Simply mix all dry ingredients with wet ingredients and blend altogether. Bake for 45 min on 180 degrees. Decorate with some melted vegan chocolate ',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/qxutws1486978099.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=C3pAgB7pync',
      ingredient1: 'self raising flour',
      ingredient2: 'coco sugar',
      ingredient3: 'cacao',
      ingredient4: 'baking powder',
      ingredient5: 'flax eggs',
      ingredient6: 'almond milk',
      ingredient7: 'vanilla',
      ingredient8: 'water',
      ingredient9: '',
      ingredient10: '',
      ingredient11: '',
      ingredient12: '',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: '',
      ingredient17: '',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '1 1/4 cup',
      measure2: '1/2 cup',
      measure3: '1/3 cup raw',
      measure4: '1 tsp',
      measure5: '2',
      measure6: '1/2 cup',
      measure7: '1 tsp',
      measure8: '1/2 cup boiling',
      measure9: '',
      measure10: '',
      measure11: '',
      measure12: '',
      measure13: '',
      measure14: '',
      measure15: '',
      measure16: '',
      measure17: '',
      measure18: '',
      measure19: '',
      measure20: ''
    },
    {
      id: '52819',
      mealName: 'Cajun spiced fish tacos',
      mealCategory: 'Seafood',
      instructions: 'Cooking in a cajun spice and cayenne pepper marinade makes this fish super succulent and flavoursome. Top with a zesty dressing and serve in a tortilla for a quick, fuss-free main that\'s delightfully summery.\r\n\r\nOn a large plate, mix the cajun spice and cayenne pepper with a little seasoning and use to coat the fish all over.\r\n\r\nHeat a little oil in a frying pan, add in the fish and cook over a medium heat until golden. Reduce the heat and continue frying until the fish is cooked through, about 10 minutes. Cook in batches if you don’t have enough room in the pan.\r\n\r\nMeanwhile, prepare the dressing by combining all the ingredients with a little seasoning.\r\nSoften the tortillas by heating in the microwave for 5-10 seconds. Pile high with the avocado, lettuce and spring onion, add a spoonful of salsa, top with large flakes of fish and drizzle over the dressing.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=N4EdUt0Ou48',
      ingredient1: 'cajun',
      ingredient2: 'cayenne pepper',
      ingredient3: 'white fish',
      ingredient4: 'vegetable oil',
      ingredient5: 'flour tortilla',
      ingredient6: 'avocado',
      ingredient7: 'little gem lettuce',
      ingredient8: 'spring onion',
      ingredient9: 'salsa',
      ingredient10: 'sour cream',
      ingredient11: 'lemon',
      ingredient12: 'garlic',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: '',
      ingredient17: '',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '2 tbsp',
      measure2: '1 tsp',
      measure3: '4 fillets',
      measure4: '1 tsp',
      measure5: '8',
      measure6: '1 sliced',
      measure7: '2 shredded',
      measure8: '4 shredded',
      measure9: '1 x 300ml',
      measure10: '1 pot',
      measure11: '1',
      measure12: '1 clove finely chopped',
      measure13: '',
      measure14: '',
      measure15: '',
      measure16: '',
      measure17: '',
      measure18: '',
      measure19: '',
      measure20: ''
    },
    {
      id: '52777',
      mealName: 'Mediterranean Pasta Salad',
      mealCategory: 'Seafood',
      instructions: 'Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\r\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=e52IL8zYmaE',
      ingredient1: 'mozzarella balls',
      ingredient2: 'baby plum tomatoes',
      ingredient3: 'fresh basil',
      ingredient4: 'farfalle',
      ingredient5: 'extra virgin olive oil',
      ingredient6: 'Green Olives',
      ingredient7: 'tuna',
      ingredient8: 'salt',
      ingredient9: 'pepper',
      ingredient10: '',
      ingredient11: '',
      ingredient12: '',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: null,
      ingredient17: null,
      ingredient18: null,
      ingredient19: null,
      ingredient20: null,
      measure1: '200 g',
      measure2: '250 g',
      measure3: '1  bunch',
      measure4: '350 g',
      measure5: '3  tablespoons',
      measure6: '40 g',
      measure7: '200 g',
      measure8: 'to taste',
      measure9: 'to taste',
      measure10: '',
      measure11: '',
      measure12: '',
      measure13: '',
      measure14: '',
      measure15: '',
      measure16: null,
      measure17: null,
      measure18: null,
      measure19: null,
      measure20: null
    },
    {
      id: '52993',
      mealName: 'Honey Balsamic Chicken with Crispy Broccoli & Potatoes',
      mealCategory: 'Chicken',
      instructions: '2 Servings\r\n\r\n1. Preheat oven to 425 degrees. Wash and dry all produce. Cut potatoes into 1/2-inch-thick wedges. Toss on one side of a baking sheet with a drizzle of oil, salt, and pepper. (For 4 servings, spread potatoes out across entire sheet.) Roast on top rack for 5 minutes (we\'ll add the broccoli then). \r\n\r\n2. Meanwhile, cut broccoli florets into bite-size pieces, if necessary. Peel and finely chop garlic. In a small microwave-safe bowl, combine 1 TBSP olive oil (2 TBSP for 4 servings) and half the garlic. Microwave until garlic sizzles, 30 seconds. \r\n\r\n3. Once potatoes have roasted 5 minutes, remove sheet from oven and add broccoli to empty side; carefully toss with garlic oil, salt, and pepper. (For 4 servings, add broccoli to a second sheet.) Continue roasting until potatoes and broccoli are browned and crispy, 15-20 minutes more. \r\n\r\n4. While veggies roast, pat chicken dry with paper towels; season all over with salt and pepper. Heat a drizzle of oil in a large pan over medium-high heat. Add chicken and cook until browned and cooked through, 5-6 minutes per side. (If chicken browns too quickly, reduce heat to medium.) Turn off heat; set chicken aside to rest. Wash out pan. \r\n\r\n5. Heat pan used for chicken over medium-high heat. Add a drizzle of oil and remaining garlic; cook until fragrant, 30 seconds. Stir in vinegar, honey, stock concentrate, and 1/4 cup water (1/3 cup for 4 servings). Simmer until thick and glossy, 2-3 minutes. Remove from heat and stir in 1 TBSP butter (2 TBSP for 4). Season with salt and pepper. \r\n\r\n6. Return chicken to pan and turn to coat in glaze. Divide chicken, broccoli, and potatoes between plates. Spoon any remaining glaze over chicken and serve. ',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/kvbotn1581012881.jpg',
      mealVideo: '',
      ingredient1: 'Potatoes',
      ingredient2: 'Broccoli',
      ingredient3: 'Garlic',
      ingredient4: 'Chicken Breast',
      ingredient5: 'Balsamic Vinegar',
      ingredient6: 'Honey',
      ingredient7: 'Chicken Stock',
      ingredient8: 'Butter',
      ingredient9: 'Vegetable Oil',
      ingredient10: 'Olive Oil',
      ingredient11: '',
      ingredient12: '',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: '',
      ingredient17: '',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '5',
      measure2: '1',
      measure3: '2 cloves',
      measure4: '2',
      measure5: ' ',
      measure6: ' ',
      measure7: ' ',
      measure8: '1 tbsp',
      measure9: '1 tbsp',
      measure10: '1 tbsp',
      measure11: ' ',
      measure12: ' ',
      measure13: ' ',
      measure14: ' ',
      measure15: ' ',
      measure16: ' ',
      measure17: ' ',
      measure18: ' ',
      measure19: ' ',
      measure20: ' '
    },
    {
      id: '52931',
      mealName: 'Sugar Pie',
      mealCategory: 'Dessert',
      instructions: 'Preheat oven to 350 degrees F (175 degrees C). Grease a 9-inch pie dish.\r\nPlace the brown sugar and butter in a mixing bowl, and beat them together with an electric mixer until creamy and very well combined, without lumps. Beat in eggs, one at a time, incorporating the first egg before adding the next one. Add the vanilla extract and salt; beat the flour in, a little at a time, and then the milk, making a creamy batter. Pour the batter into the prepared pie dish.\r\nBake in the preheated oven for 35 minutes; remove pie, and cover the rim with aluminum foil to prevent burning. Return to oven, and bake until the middle sets and the top forms a crusty layer, about 15 more minutes. Let the pie cool to room temperature, then refrigerate for at least 1 hour before serving.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/yrstur1511816601.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=uVQ66jiL-Dc',
      ingredient1: 'Brown Sugar',
      ingredient2: 'Butter',
      ingredient3: 'Eggs',
      ingredient4: 'Vanilla Extract',
      ingredient5: 'Salt',
      ingredient6: 'Plain Flour',
      ingredient7: 'Milk',
      ingredient8: '',
      ingredient9: '',
      ingredient10: '',
      ingredient11: '',
      ingredient12: '',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: '',
      ingredient17: '',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '2 cups ',
      measure2: '¼ cup',
      measure3: '2',
      measure4: '1 tsp ',
      measure5: '1 tsp ',
      measure6: '½ cup ',
      measure7: '1 1/2 cups ',
      measure8: '',
      measure9: '',
      measure10: '',
      measure11: '',
      measure12: '',
      measure13: '',
      measure14: '',
      measure15: '',
      measure16: '',
      measure17: '',
      measure18: '',
      measure19: '',
      measure20: ''
    },
    {
      id: '52829',
      mealName: 'Grilled Mac and Cheese Sandwich',
      mealCategory: 'Pasta',
      instructions: 'Make the mac and cheese\r\n\r\n1. Bring a medium saucepan of generously salted water (you want it to taste like seawater) to a boil. Add the pasta and cook, stirring occasionally, until al dente, 8 to 10 minutes, or according to the package directions. The pasta should be tender but still chewy.\r\n2. While the pasta is cooking, in a small bowl, whisk together the flour, mustard powder, garlic powder, salt, black pepper, and cayenne pepper.\r\n3. Drain the pasta in a colander. Place the empty pasta pan (no need to wash it) over low heat and add the butter. When the butter has melted, whisk in the flour mixture and continue to cook, whisking frequently, until the mixture is beginning to brown and has a pleasant, nutty aroma, about 1 minute. Watch carefully so it does not scorch on the bottom of the pan.\r\n4. Slowly whisk the milk and cream into the flour mixture until everything is really well combined. Cook, whisking constantly, until the sauce is heated through and just begins to thicken, about 2 minutes. Remove from the heat. Gradually add the cheese while stirring constantly with a wooden spoon or silicone spatula and keep stirring until the cheese has melted into the sauce. Then stir in the drained cooked pasta.\r\n5. Line a 9-by-13-inch (23-by-33-centimeter) rimmed baking sheet with parchment paper or aluminum foil. Coat the paper or foil with nonstick cooking spray or slick it with butter. Pour the warm mac and cheese onto the prepared baking sheet and spread it evenly with a spatula. Coat another piece of parchment paper with cooking spray or butter and place it, oiled or buttered side down, directly on the surface of the mac and cheese. Refrigerate until cool and firm, about 1 hour.\r\n\r\nMake the grilled cheese\r\n6. Heat a large cast-iron or nonstick skillet over medium-low heat.\r\n7. In a small bowl, stir together the 4 tablespoons (55 grams) butter and garlic powder until well blended.\r\n8. Remove the mac and cheese from the refrigerator and peel off the top layer of parchment paper. Carefully cut into 8 equal pieces. Each piece will make 1 grilled mac and cheese sandwich. (You can stash each individual portion in a double layer of resealable plastic bags and refrigerate for up to 3 days or freeze it for up to 1 month.)\r\n9. Spread 3/4 teaspoon garlic butter on one side of each bread slice. Place half of the slices, buttered-side down, on a clean cutting board. Top each with one slice of Cheddar, then 1 piece of the mac and cheese. (Transfer from the baking sheet by scooting your hand or a spatula under each piece of mac and cheese and then flipping it over onto a sandwich.) Place 1 slice of Jack on top of each. Finish with the remaining bread slices, buttered-side up.\r\n10. Using a wide spatula, place as many sandwiches in the pan as will fit without crowding it. Cover and cook until the bottoms are nicely browned, about 4 minutes. Turn and cook until the second sides are browned, the cheese is melted, and the mac and cheese is heated through, about 4 minutes more.\r\n11. Repeat with the remaining ingredients. Cut the sandwiches in half, if desired, and serve.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/xutquv1505330523.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=PYq31xLj-DY',
      ingredient1: 'Macaroni',
      ingredient2: 'Plain Flour',
      ingredient3: 'Mustard Powder',
      ingredient4: 'Garlic powder',
      ingredient5: 'Kosher salt',
      ingredient6: 'Black pepper',
      ingredient7: 'Cayenne pepper',
      ingredient8: 'Butter',
      ingredient9: 'Whole Milk',
      ingredient10: 'Heavy Cream',
      ingredient11: 'Monterey Jack Cheese',
      ingredient12: 'Butter',
      ingredient13: 'garlic powder',
      ingredient14: 'Bread',
      ingredient15: 'Cheddar Cheese',
      ingredient16: 'Colby Jack Cheese',
      ingredient17: 'Butter',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '8 ounces (230 grams)',
      measure2: '1/3 cup',
      measure3: '3/4 teaspoon',
      measure4: '1/2 teaspoon',
      measure5: '1/2 teaspoon',
      measure6: '1/2 teaspoon',
      measure7: '1/8 teaspoon',
      measure8: '6 tablespoons (85 grams)',
      measure9: '1 1/2 cups (360 milliliters)',
      measure10: '1 cup (240 milliliters)',
      measure11: '1 pound (455 grams) ',
      measure12: '4 tablespoons (55 grams)',
      measure13: '1 teaspoon',
      measure14: '16 slices square',
      measure15: '8 slices mild',
      measure16: '8 slices',
      measure17: '4 tablespoons (55 grams)',
      measure18: '',
      measure19: '',
      measure20: ''
    },
    {
      id: '52773',
      mealName: 'Honey Teriyaki Salmon',
      mealCategory: 'Seafood',
      instructions: 'Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=4MpYuaJsvRw',
      ingredient1: 'Salmon',
      ingredient2: 'Olive oil',
      ingredient3: 'Soy Sauce',
      ingredient4: 'Sake',
      ingredient5: 'Sesame Seed',
      ingredient6: '',
      ingredient7: '',
      ingredient8: '',
      ingredient9: '',
      ingredient10: '',
      ingredient11: '',
      ingredient12: '',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: null,
      ingredient17: null,
      ingredient18: null,
      ingredient19: null,
      ingredient20: null,
      measure1: '1 lb',
      measure2: '1 tablespoon',
      measure3: '2 tablespoons',
      measure4: '2 tablespoons',
      measure5: '4 tablespoons',
      measure6: '',
      measure7: '',
      measure8: '',
      measure9: '',
      measure10: '',
      measure11: '',
      measure12: '',
      measure13: '',
      measure14: '',
      measure15: '',
      measure16: null,
      measure17: null,
      measure18: null,
      measure19: null,
      measure20: null
    },
    {
      id: '52982',
      mealName: 'Spaghetti alla Carbonara',
      mealCategory: 'Pasta',
      instructions: 'Per preparare gli spaghetti alla carbonara cominciate mettendo sul fuoco una pentola con l’acqua salata per cuocere la pasta. Nel frattempo eliminate la cotenna dal guanciale  e tagliatelo prima a fette e poi a striscioline spesse circa 1cm . La cotenna avanzata potrà essere riutilizzata per insaporire altre preparazioni. Versate i pezzetti in una padella antiaderente e rosolate per circa 15 minuti a fiamma media, fate attenzione a non bruciarlo altrimenti rilascerà un aroma troppo forte.\r\n\r\nNel frattempo tuffate gli spaghetti nell’acqua bollente e cuoceteli per il tempo indicato sulla confezione. Intanto versate i tuorli in una ciotola, aggiungete anche la maggior parte del pecorino previsto dalla ricetta la parte restante servirà per guarnire la pasta.\r\n\r\nInsaporite con il pepe nero, amalgamate tutto con una frusta a mano. Aggiungete un cucchiaio di acqua di cottura per diluire il composto e mescolate.\r\n\r\n\r\nIntanto il guanciale sarà giunto a cottura, spegnete il fuoco e tenetelo da parte. Scolate la pasta al dente direttamente nel tegame con il guanciale e saltatela brevemente per insaporirla. Togliete dal fuoco e versate il composto di uova e pecorino nel tegame, saltate la pasta per amalgamare\r\n\r\n\r\ne se dovesse risultare troppo asciutta potete aggiungere poca acqua di cottura. Servite subito gli spaghetti alla carbonara insaporendoli con il pecorino avanzato e il pepe nero macinato.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=_T6jkRvhlkk',
      ingredient1: 'Spaghetti',
      ingredient2: 'Egg Yolks',
      ingredient3: 'Salt',
      ingredient4: 'Bacon',
      ingredient5: 'Pecorino',
      ingredient6: 'Black Pepper',
      ingredient7: '',
      ingredient8: '',
      ingredient9: '',
      ingredient10: '',
      ingredient11: '',
      ingredient12: '',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: '',
      ingredient17: '',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '320g',
      measure2: '6',
      measure3: 'As required',
      measure4: '150g',
      measure5: '50g',
      measure6: 'As required',
      measure7: ' ',
      measure8: ' ',
      measure9: ' ',
      measure10: ' ',
      measure11: ' ',
      measure12: ' ',
      measure13: ' ',
      measure14: ' ',
      measure15: ' ',
      measure16: ' ',
      measure17: ' ',
      measure18: ' ',
      measure19: ' ',
      measure20: ' '
    },
    {
      id: '52952',
      mealName: 'Beef Lo Mein',
      mealCategory: 'Beef',
      instructions: 'STEP 1 - MARINATING THE BEEF\r\nIn a bowl, add the beef, salt, 1 pinch white pepper, 1 Teaspoon sesame seed oil, 1/2 egg, corn starch,1 Tablespoon of oil and mix together.\r\nSTEP 2 - BOILING THE THE NOODLES\r\nIn a 6 qt pot add your noodles to boiling water until the noodles are submerged and boil on high heat for 10 seconds. After your noodles is done boiling strain and cool with cold water.\r\nSTEP 3 - STIR FRY\r\nAdd 2 Tablespoons of oil, beef and cook on high heat untill beef is medium cooked.\r\nSet the cooked beef aside\r\nIn a wok add 2 Tablespoon of oil, onions, minced garlic, minced ginger, bean sprouts, mushrooms, peapods and 1.5 cups of water or until the vegetables are submerged in water.\r\nAdd the noodles to wok\r\nTo make the sauce, add oyster sauce, 1 pinch white pepper, 1 teaspoon sesame seed oil, sugar, and 1 Teaspoon of soy sauce.\r\nNext add the beef to wok and stir-fry',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/1529444830.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=ZT9LSsNXXe0',
      ingredient1: 'Beef',
      ingredient2: 'Salt',
      ingredient3: 'Pepper',
      ingredient4: 'Sesame Seed Oil',
      ingredient5: 'Egg',
      ingredient6: 'Starch',
      ingredient7: 'Oil',
      ingredient8: 'Noodles',
      ingredient9: 'Onion',
      ingredient10: 'Minced Garlic',
      ingredient11: 'Ginger',
      ingredient12: 'Bean Sprouts',
      ingredient13: 'Mushrooms',
      ingredient14: 'Water',
      ingredient15: 'Oyster Sauce',
      ingredient16: 'Sugar',
      ingredient17: 'Soy Sauce',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '1/2 lb',
      measure2: 'pinch',
      measure3: 'pinch',
      measure4: '2 tsp',
      measure5: '1/2 ',
      measure6: '3 tbs',
      measure7: '5 tbs',
      measure8: '1/4 lb',
      measure9: '1/2 cup ',
      measure10: '1 tsp ',
      measure11: '1 tsp ',
      measure12: '1 cup ',
      measure13: '1 cup ',
      measure14: '1 cup ',
      measure15: '1 tbs',
      measure16: '1 tsp ',
      measure17: '1 tsp ',
      measure18: '',
      measure19: '',
      measure20: ''
    },
    {
      id: '52908',
      mealName: 'Ratatouille',
      mealCategory: 'Vegetarian',
      instructions: 'Cut the aubergines in half lengthways. Place them on the board, cut side down, slice in half lengthways again and then across into 1.5cm chunks. Cut off the courgettes ends, then across into 1.5cm slices. Peel the peppers from stalk to bottom. Hold upright, cut around the stalk, then cut into 3 pieces. Cut away any membrane, then chop into bite-size chunks.\r\nScore a small cross on the base of each tomato, then put them into a heatproof bowl. Pour boiling water over the tomatoes, leave for 20 secs, then remove. Pour the water away, replace the tomatoes and cover with cold water. Leave to cool, then peel the skin away. Quarter the tomatoes, scrape away the seeds with a spoon, then roughly chop the flesh.\r\nSet a sauté pan over medium heat and when hot, pour in 2 tbsp olive oil. Brown the aubergines for 5 mins on each side until the pieces are soft. Set them aside and fry the courgettes in another tbsp oil for 5 mins, until golden on both sides. Repeat with the peppers. Don’t overcook the vegetables at this stage, as they have some more cooking left in the next step.\r\nTear up the basil leaves and set aside. Cook the onion in the pan for 5 mins. Add the garlic and fry for a further min. Stir in the vinegar and sugar, then tip in the tomatoes and half the basil. Return the vegetables to the pan with some salt and pepper and cook for 5 mins. Serve with basil.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=BFdQUgAFtGU',
      ingredient1: 'Aubergine',
      ingredient2: 'Courgettes',
      ingredient3: 'Yellow Pepper',
      ingredient4: 'Tomato',
      ingredient5: 'Olive Oil',
      ingredient6: 'Basil',
      ingredient7: 'Onion',
      ingredient8: 'Garlic Clove',
      ingredient9: 'Red Wine Vinegar',
      ingredient10: 'Sugar',
      ingredient11: '',
      ingredient12: '',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: '',
      ingredient17: '',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: '2 large',
      measure2: '4',
      measure3: '2',
      measure4: '4 large',
      measure5: '5 tbs',
      measure6: 'Bunch',
      measure7: '1 medium',
      measure8: '3 finely chopped',
      measure9: '1 tsp ',
      measure10: '1 tsp ',
      measure11: '',
      measure12: '',
      measure13: '',
      measure14: '',
      measure15: '',
      measure16: '',
      measure17: '',
      measure18: '',
      measure19: '',
      measure20: ''
    },
    {
      id: '52804',
      mealName: 'Poutine',
      mealCategory: 'Miscellaneous',
      instructions: 'Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\nWarm gravy in saucepan or microwave.\r\nPlace the fries into the hot oil, and cook until light brown, about 5 minutes.\r\nRemove to a paper towel lined plate to drain.\r\nPlace the fries on a serving platter, and sprinkle the cheese over them.\r\nLadle gravy over the fries and cheese, and serve immediately.',
      mealNameThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      mealVideo: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      ingredient1: 'Vegetable Oil',
      ingredient2: 'Beef Gravy',
      ingredient3: 'Potatoes',
      ingredient4: 'Cheese Curds',
      ingredient5: '',
      ingredient6: '',
      ingredient7: '',
      ingredient8: '',
      ingredient9: '',
      ingredient10: '',
      ingredient11: '',
      ingredient12: '',
      ingredient13: '',
      ingredient14: '',
      ingredient15: '',
      ingredient16: '',
      ingredient17: '',
      ingredient18: '',
      ingredient19: '',
      ingredient20: '',
      measure1: 'Dash',
      measure2: '1 Can',
      measure3: '5 thin cut',
      measure4: '2 cups',
      measure5: '',
      measure6: '',
      measure7: '',
      measure8: '',
      measure9: '',
      measure10: '',
      measure11: '',
      measure12: '',
      measure13: '',
      measure14: '',
      measure15: '',
      measure16: '',
      measure17: '',
      measure18: '',
      measure19: '',
      measure20: ''
    }
  ];
  
  export default recipes;